# Generated by Django 4.2.1 on 2023-06-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditapplication',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='credit_application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='credit.creditapplication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='credit_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='credit.creditapplication'),
        ),
        migrations.DeleteModel(
            name='ProductInCreditApplication',
        ),
    ]
